version: '2'

services:
    app:
        image: 'springboot:v3'
        build:
            context: .
        container_name: app
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=1234
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        expose:
            - 8080
        ports:
            - 8080:8080
    db:
        image: 'postgres:latest'
        container_name: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
